# Generated by Django 5.1 on 2024-11-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id_videojuego', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('compañia', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('fecha_lanzamiento', models.DateField()),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
