# Generated by Django 5.1.2 on 2024-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
