# Generated by Django 5.1.2 on 2024-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_alter_clientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(height_field=100, upload_to='img/', width_field=100),
        ),
    ]
