# Generated by Django 5.1.2 on 2024-11-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0003_alter_clientes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
